### ISSUE TITLE
Make codebase rustfmt happy

### ISSUE THREAD

**Issue by imp** [ideasman42/rangetree-rs#1]
Nice package !

I see that your code style differs significantly from rustfmt. Would you accept contributions to change it along the rustfmt guidelines ?

**Comment by ideasman42** [comment]
Hi, thanks! As for following rustfmt, I'm not totally against, but rather not use its default multi-line argument alignment. It right-shifts too much, causing diff-noise on changes to function signature IMHO.

Otherwise I didn't think the code style was so different to Rusts? (brace placement, indentation... etc).
I tried using rustfmt a while ago and ran into some bugs (was crashing, also messing up comments). So happy to try again but also not wanting to spend too much time messing around if its not able to be configured with enough flexibility.

Last I tried using rustfmt, make up with this `rustfmt.toml` which was close to my preferred formatting:

Tested again and it seemed OK, although in parts it joins items in a lists when I'd prefer not, there are some other details Im not totally happy with either.

```.toml
enum_trailing_comma = true
fn_args_layout = "Block"
fn_args_paren_newline = true
fn_args_density = "Vertical"
fn_brace_style = "AlwaysNextLine"
struct_lit_multiline_style = "ForceMulti"
struct_lit_trailing_comma = "Always"
struct_trailing_comma = "Always"
where_trailing_comma = true
normalize_comments = false
```

**Comment by ideasman42** [comment]
Trying rustfmt on a [larger codebase](https://gitlab.com/ideasman42/bmesh-rs) and not really happy with it, running it once results in code that doesn't build. Also it misses [block indentation for vector's](https://github.com/rust-lang-nursery/rustfmt/issues/1331).

So I'm not exactly against, but find it not stable/reliable enough to apply to a code-base.
